### ISSUE TITLE
DROID install errors out

### ISSUE THREAD

**Issue by nkrabben** [mistydemeo/homebrew-digipres#14]
Looks like an old version is linked? I don't fully understand how brew works. Here's the error I get.

Error: An exception occured within a build process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 45d8928f1425c1c0fbc0f8fb3dea9f07a0fe6848d0dd4696e15da1c52152d627
Actual: f6aae4357064d27e121ae964ca587254aa2d3897c00b9ff488865737d7ea86b1

**Comment by mistydemeo** [comment]
Looks like the tarball was updated in-place at some point. I'll do an update - sorry for this!

**Comment by mistydemeo** [comment]
Should be fixed now, sorry for the inconvenience!
